lws_blacklight/config/routes.rb
require 'lucid/prism' 

LwsBlacklight::Application.routes.draw do
  get 'catalog/opensearch', :as => "opensearch_catalog"
  get 'catalog/email', :as => "email_catalog"
  post 'catalog/email'
  get "catalog/facet/:id", :to => 'catalog#facet', :as => 'catalog_facet'
  get "catalog", :to => 'catalog#index', :as => 'catalog_index'

  get 'catalog/:collection_id', :to => 'catalog#index', :as => 'collection' 

  get 'bookmarks' => 'bookmarks#index', :as => 'bookmarks'
  delete 'bookmarks/clear' => 'bookmarks#clear', :as => 'clear_bookmarks'
  put 'bookmark' => 'bookmarks#create', :as => 'bookmark'
  delete 'bookmark' => 'bookmarks#destroy', :as => 'bookmark'

  Blacklight.add_routes(self, :except => [:bookmarks, :catalog])
  
  devise_for :users
  
  match "prism" => Lucid::Prism, :anchor => false 
  
  root :to => "collections#index"
  

end

lws_blacklight/app/controllers/catalog_controller.rb
# -*- encoding : utf-8 -*-
require 'blacklight/catalog'

class CatalogController < BaseController
  layout 'lws_blacklight'
  
  include Blacklight::Catalog
  
  # get search results from the solr index
  def index
    if current_collection.name.blank? || current_collection.document_count == 0 
      redirect_to root_path 
    else
      extra_head_content << view_context.auto_discovery_link_tag(:rss, url_for(params.merge(:format => 'rss')), :title => t('blacklight.search.rss_feed') )
      extra_head_content << view_context.auto_discovery_link_tag(:atom, url_for(params.merge(:format => 'atom')), :title => t('blacklight.search.atom_feed') )
      
      (@response, @document_list) = get_search_results
      @filters = params[:f] || []
      
      respond_to do |format|
        format.html { save_current_search_params }
        format.rss  { render :layout => false }
        format.atom { render :layout => false }
      end
    end
  end
  
  configure_blacklight do |config|
    ## Default parameters to send to solr for all search-like requests. See also SolrHelper#solr_search_params
    config.default_solr_params = { 
      :qt => '/lucid',
      :'hl.simple.pre' => '<b>',
      :'hl.simple.post' => '</b>',
      :req_type => 'main', # see http://docs.lucidworks.com/display/lweug/Constructing+Solr+Queries
      :'hl.fragsize' => 250,
      :rows => 10
    }

    ## Default parameters to send on single-document requests to Solr. These settings are the Blackligt defaults (see SolrHelper#solr_doc_params) or 
    ## parameters included in the Blacklight-jetty document requestHandler.
    config.default_document_solr_params = {
     :qt => '/lucid',
     :fl => '*',
     :rows => 1,
     :q => '{!raw f=id v=$id}' 
    }

    ## solr field configuration for search results/index views
    # config.index.show_link = 'name'
    # config.index.record_display_type = 'format'

    ## solr field configuration for document/show views
    # config.show.html_title = 'name'
    # config.show.heading = 'name'
    # config.show.display_type = 'format'

    # solr fields that will be treated as facets by the blacklight application
    #   The ordering of the field names is the order of the display
    #
    # Setting a limit will trigger Blacklight's 'more' facet values link.
    # * If left unset, then all facet values returned by solr will be displayed.
    # * If set to an integer, then "f.somefield.facet.limit" will be added to
    # solr request, with actual solr request being +1 your configured limit --
    # you configure the number of items you actually want _displayed_ in a page.    
    # * If set to 'true', then no additional parameters will be sent to solr,
    # but any 'sniffed' request limit parameters will be used for paging, with
    # paging at requested limit -1. Can sniff from facet.limit or 
    # f.specific_field.facet.limit solr request params. This 'true' config
    # can be used if you set limits in :default_solr_params, or as defaults
    # on the solr side in the request handler itself. Request handler defaults
    # sniffing requires solr requests to be made with "echoParams=all", for
    # app code to actually have it echo'd back to see it.  
    #
    # :show may be set to false if you don't want the facet to be drawn in the 
    # facet bar
    # config.add_facet_field 'author_display', :label=> 'Author'
    # config.add_facet_field 'mimeType', :label=> 'Document Type'

    # config.add_facet_field 'example_pivot_field', :label => 'Pivot Field', :pivot => ['format', 'language_facet']

    # config.add_facet_field 'example_query_facet_field', :label => 'Publish Date', :query => {
    #    :years_5 => { :label => 'within 5 Years', :fq => "pub_date:[#{Time.now.year - 5 } TO *]" },
    #    :years_10 => { :label => 'within 10 Years', :fq => "pub_date:[#{Time.now.year - 10 } TO *]" },
    #    :years_25 => { :label => 'within 25 Years', :fq => "pub_date:[#{Time.now.year - 25 } TO *]" }
    # }

    ## Have BL send all facet field names to Solr, which has been the default
    ## previously. Simply remove these lines if you'd rather use Solr request
    ## handler defaults, or have no facets.
    # config.add_facet_fields_to_solr_request!

    ## solr fields to be displayed in the index (search results) view
    ##   The ordering of the field names is the order of the display 
    # config.add_index_field 'body', :label => 'Body:'  # this was made unnecessary by changes to BlacklightHelper

    # solr fields to be displayed in the show (single result) view
    #   The ordering of the field names is the order of the display 
    config.add_show_field 'description', :label => 'Description:' 

    # "fielded" search configuration. Used by pulldown among other places.
    # For supported keys in hash, see rdoc for Blacklight::SearchFields
    #
    # Search fields will inherit the :qt solr request handler from
    # config[:default_solr_parameters], OR can specify a different one
    # with a :qt key/value. Below examples inherit, except for subject
    # that specifies the same :qt as default for our own internal
    # testing purposes.
    #
    # The :key is what will be used to identify this BL search field internally,
    # as well as in URLs -- so changing it after deployment may break bookmarked
    # urls.  A display label will be automatically calculated from the :key,
    # or can be specified manually to be different. 

    # This one uses all the defaults set by the solr request handler. Which
    # solr request handler? The one set in config[:default_solr_parameters][:qt],
    # since we aren't specifying it otherwise. 
    
    config.add_search_field 'all_fields', :label => 'All Fields'
    

    # Now we see how to over-ride Solr request handler defaults, in this
    # case for a BL "search field", which is really a dismax aggregate
    # of Solr search fields. 
    
    config.add_search_field('title') do |field|
      field.solr_parameters = { :qf => 'title', :pf => 'title' }
    end
    
    config.add_search_field('author') do |field|
      field.solr_parameters = { :qf => 'author', :pf => 'author' }
    end
    
    # "sort results by" select (pulldown)
    # label in pulldown is followed by the name of the SOLR field to sort by and
    # whether the sort is ascending or descending (it must be asc or desc
    # except in the relevancy case).
    config.add_sort_field 'score desc', :label => 'relevance'
    config.add_sort_field 'lastModified desc', :label => 'Last modified'

    # If there are more than this many search results, no spelling ("did you 
    # mean") suggestion is offered.
    config.spell_max = 5
  end
  
  # #email overridden to add catalog_id to the redirects
  # Email Action (this will render the appropriate view on GET requests and process the form and send the email on POST requests)
  def email
    @response, @documents = get_solr_response_for_field_values(SolrDocument.unique_key,params[:id])
    if request.post?
      if params[:to]
        url_gen_params = {:host => request.host_with_port, :protocol => request.protocol}
        
        if params[:to].match(/^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}$/)
          email = RecordMailer.email_record(@documents, {:to => params[:to], :message => params[:message]}, url_gen_params)
        else
          flash[:error] = I18n.t('blacklight.email.errors.to.invalid', :to => params[:to])
        end
      else
        flash[:error] = I18n.t('blacklight.email.errors.to.blank')
      end

      unless flash[:error]
        email.deliver 
        flash[:success] = "Email sent"
        redirect_to catalog_path(params['id'], :collection_id => params[:collection_id]) unless request.xhr?
      end
    end

    unless !request.xhr? && flash[:success]
      respond_to do |format|
        format.js { render :layout => false }
        format.html
      end
    end
  end
  
  
  # Overrride Blacklight's solr_search_params to add current user's role(s) to the request, honoring LWS role filters
  def solr_search_params(user_params = params || {})
    # Adapted from lwe-ui's search.rb#roles_for(user,collection)
    roles = []
    if current_collection.roles && current_user
      
      # ==> [{"users":["admin"],"name":"DEFAULT","filters":["*:*"],"groups":[]},{"users":["bob"],"name":"restricted","filters":["-search"],"groups":[]}]
      
      current_collection.roles.each do |role|
        roles << role["name"] if role["users"].include?(current_user.username)
      end
    end
    
    super.merge :role => roles
  end

  # Overriding blacklight_solr_config, but this is how it is accessed
  # def blacklight_solr
  #   @solr ||=  RSolr.connect(blacklight_solr_config)
  # end
  def blacklight_solr_config
    # Make the Solr URL dynamic based on the users session set collection, removes need/use of config/solr.yml
    # TODO: need to see how this will affect test runs
    # See also use of ENV['LWS_...'] in collection_manager_controller
    url ||= ENV['LWS_SOLR_URL']
    url ||= "#{ENV['LWS_CORE_URL']}/solr" if ENV['LWS_CORE_URL']
    {:url => "#{url || 'http://127.0.0.1:8888/solr'}/#{current_collection.name}"}
  end
end 

lws_blacklight/app/helpers/catalog_helper.rb
# Overrides to Blacklights facet handling
# to allow facets returned in the response to automatically render rather than having to be configured in the app via Blacklight configuration

module CatalogHelper
  include Blacklight::CatalogHelperBehavior
  
  # Pass in an RSolr::Response. Displays the "X Documents Found" message.
  def render_documents_info(response, options = {})
    total_num = response.response[:numFound]
    case total_num
      when 0; t('blacklight.search.documents.total.no_items_found', :total_num => total_num).html_safe
      when 1; t('blacklight.search.documents.total.one', :total_num => total_num).html_safe
      else; t('blacklight.search.documents.total.other', :total_num => total_num).html_safe
    end
  end
end

lws_blacklight/app/views/catalog/_bookmark_control.html.erb
<% if current_or_guest_user %>
  <%- existing_bookmark = current_or_guest_user.existing_bookmark_for(document.id) -%>
  <%- 
  # Note these two forms are pretty similar but for different :methods, classes, and labels. 
  # but it was simpler to leave them seperate instead of DRYing them, got confusing trying that.
  # the data-doc-id attribute is used by our JS that converts to a checkbox/label.
  -%>  
  <% unless existing_bookmark %>  

      <%= form_tag( bookmark_path( :id => document.id ), :method => :put, :class => "bookmark_toggle", "data-doc-id" => document.id) do %>   
        <%= submit_tag(t('blacklight.bookmarks.add.button'), :id => "bookmark_toggle_#{document.id.to_s.parameterize}", :class => "bookmark_add") %>
      <% end %>
  
  <% else %>
  
      <%= form_tag( bookmark_path( :id => document.id  ), :method => :delete, :class => "bookmark_toggle", "data-doc-id" => document.id) do %>  
        <%= submit_tag(t('blacklight.bookmarks.remove.button'), :id => "bookmark_toggle_#{document.id.to_s.parameterize}", :class => "bookmark_remove") %>
      <% end %>
      
  <% end %>
<% else %>
  &nbsp;
<% end %>

lws_blacklight/app/views/catalog/_constraints.html.erb
<div id="appliedParams" class="constraints-container">
  <span class="constraints-label"><%= t('blacklight.search.filters.title') %></span>
  <div class="constraints-options"> 
    <% if query_has_filters? %>
      <div class="btn-group">
        <%= link_to (t('blacklight.search.view_filters') + content_tag(:span, '', :class => 'caret')).html_safe, '#', 'data-toggle' => 'collapse', 'data-target' => '#applied-filters', :class => 'btn btn-toggle collapsed' %>
      </div>
    <% end %>
    <% if has_query? || query_has_filters? %>
      <div class="btn-group">
        <%= link_to t('blacklight.search.clear_all'), url_for(:action=>'index'), :class => "btn" %>
      </div>
    <% end %>
  </div>
  <%= render_constraints(params) %>  
</div>

lws_blacklight/app/views/catalog/_constraints_element.html.erb
<%- # local params:
    # label 
    # value
    # options =>
    #   :remove => url for a remove constraint link
    #   :classes => array of classes to add to container span
    options ||= {}
    options[:escape_label] = true unless options.has_key?(:escape_label)
    options[:escape_value] = true unless options.has_key?(:escape_value)
-%>

<span class="applied-filter constraint <%= options[:classes].join(" ") if options[:classes] %>">
  <%- unless options[:remove].blank? -%>
    <% accessible_remove_label =               
            if label.blank?
              t('blacklight.search.filters.remove.value', :value => (options[:escape_value] ? h(value) : value))
            else
              t('blacklight.search.filters.remove.label', :label => (options[:escape_label] ? h(label) : label), :value => (options[:escape_value] ? h(value) : value))
            end              
    %>                
    <%= link_to content_tag(:span, accessible_remove_label, :class => 'is-invisible') + content_tag(:span, options[:escape_value] ? h(value) : raw(value), :class => 'filter-value') + content_tag(:i, '', :class => 'icon-remove'), options[:remove], :class=>'btn btn-link btn-filter' %>
  <%- end -%>
</span>

lws_blacklight/app/views/catalog/_document.html.erb
<% # container for a single doc -%>
<li class="document <%= render_document_class document %>">
  
  <%= render :partial => 'document_header', :locals => { :document => document, :document_counter => document_counter } %>

  <%= render :partial => 'document_body', :locals => { :document => document } %>
  
  <a class="btn btn-link btn-toggle collapsed" href="#" data-toggle="collapse" data-target="#doc<%= document_counter %>">
    more<span class="caret"></span>
  </a>

  <div id="doc<%= document_counter %>" class="collapse out">
    <% # main container for doc partial view -%>
    <%= render_document_partial document, :index %>
  </div>
</li>

lws_blacklight/app/views/catalog/_document_body.html.erb
<div class="document-body">
	<% #Load the body field, if there is one and display it -%>
	<% index_fields(document).each do |solr_fname, field| -%>
		<% if (render_index_field_label document, :field => solr_fname) == "body" -%>
			<% if should_render_index_field? document, field %>
				<p><%= render_index_field_value document, :field => solr_fname %></p>
			<% end -%>
		<% end -%>
	<% end -%>
</div>

lws_blacklight/app/views/catalog/_document_header.html.erb
<% # Overridden in order to adjust the hyperlink generated, eventually adding data source specific links 
   # header bar for doc items in index view -%>
<div class="documentHeader clearfix">
  <% # main title container for doc partial view -%>
    <h4 class="document-title span7">
      <span class="document-count"><%= t('blacklight.search.documents.counter', :counter => (document_counter + 1 + @response.params[:start].to_i)) %></span>
      <%= link_to document[:title].present? ? document[:title][0] : document.id, document.id, :target => '_blank' %>
    </h4>

  <% # bookmark functions for items/docs -%>
  <%= render_index_doc_actions document, :wrapping_class => "documentFunctions span2" %>
</div>

lws_blacklight/app/views/catalog/_document_list.html.erb
<% # container for all documents in index view -%>
<ol id="documents">
  <%= render documents, :as => :document %>
</ol>

lws_blacklight/app/views/catalog/_facet_layout.html.erb
<div class="facets-group accordion-group">
  <div class="accordion-heading">
    <a class="facets-toggle accordion-toggle collapsed" data-toggle="collapse" data-parent="#facets" href="#blacklight-<%= facet_field.field.parameterize %>">
      <%= facet_field.label %>
      <i class="icon-chevron-right"></i>
    </a>
  </div>
  <div id="blacklight-<%= facet_field.field.parameterize %>" class="accordion-body collapse">
    <div class="accordion-inner">
       <%= yield %>
    </div>
  </div>
</div>

lws_blacklight/app/views/catalog/_facet_limit.html.erb
<ul class="list-facets">
  <% paginator =
      Blacklight::Solr::FacetPaginator.new(display_facet.items,
        :limit => facet_limit_for(solr_field))
  %>
  <% paginator.items.each do |item| -%>
    <% if facet_in_params?( solr_field, item.value ) %>
        <li class="selected"><%= render_selected_facet_value(solr_field, item) %></li>
      <% else %>
        <li><%= render_facet_value(solr_field, item) %></li>
    <% end -%>
  <% end %>

  <% if (paginator.has_next?) %>
    <li class="more_facets_link"><%= link_to(t('blacklight.search.facets.more'), params.merge(:id => solr_field, :action=>"facet", :page => nil), :class => "more_facets_link") %></li>
  <% end %>
</ul>

lws_blacklight/app/views/catalog/_facets.html.erb
<% # main container for facets/limits menu -%>
<% if has_facet_values? %>
  <div id="facets" class="accordion">
    <div class="accordion-group">
      <h2>LIMIT YOUR SEARCH</h2>
    </div>
    
    <%= render_facet_partials %>
  </div>
<% end %>

lws_blacklight/app/views/catalog/_graph.html.erb
<% if has_facet_values? %>
  <div class="row">
    <div class="span9">
      <div id="graph" data-fieldname="" data-graphtype="pie"></div>
    </div>
  </div>
<% end %>

<div id="graph-msg" class="alert alert-info">Choose a facet group to view data</div>

lws_blacklight/app/views/catalog/_results_header.erb
<div class="results-header">
   <p class="results-info">
     <%= render_documents_info(@response) %>
   </p>
   
 <div class="view-options">
   <div class="btn-group">
     <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
       Analyses<span class="caret"></span>
     </a>
     <ul class="dropdown-menu select">
       <li class="selected"><a href="#" href="#">Facet Count</a></li>
     </ul>
   </div>
   
   <div id="graph-options" class="btn-group">
     <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
       Graph Type<span class="caret"></span>
     </a>
     <ul class="dropdown-menu select">
       <li><a class="graphtype" href="#" data-graphtype="bar" href="#">Bar Graph</a></li>
       <li class="selected"><a class="graphtype" href="#" data-graphtype="pie" href="#">Pie Chart</a></li>
     </ul>
   </div>
 </div>
</div>

lws_blacklight/app/views/catalog/_search_form.html.erb
<%= form_tag collection_path(current_collection.name), :method => :get, :class => 'search-query-form form-inline clearfix' do %>
  <%= search_as_hidden_fields(:omit_keys => [:q, :search_field, :qt, :page]).html_safe %>   
  <% unless search_fields.empty? %>
    <div class="pull-left">
      <label for="search_field" class="hide-text"><%= t('blacklight.search.form.search_field.label') %></label>
      <%= select_tag(:search_field, options_for_select(search_fields, h(params[:search_field])), :title => t('blacklight.search.form.search_field.title'), :class=>"search_field input-small") %>
      <span class="hide-text"><%= t('blacklight.search.form.search_field.post_label') %></span>
    </div>
  <% end %>
  <div class="input-append pull-left">
    <label for="q" class="hide-text"><%= t('blacklight.search.form.q') %></label>
     <%= text_field_tag :q, params[:q], :placeholder => t('blacklight.search.form.q'), :class => "search_q q", :id => "q"%>
    <button type="submit" class="btn btn-primary">
      <%=t('blacklight.search.form.submit')%> <i class="icon-search icon-white"></i>
    </button>
  </div>
<% end %>

lws_blacklight/app/views/catalog/index.html.erb
 <div id="sidebar" class="span3">
  <%= render :partial=>'facets' %>
</div><!--/well -->

<div id="content" class="span9">
  <h2 class="hide-text top-content-title"><%= t('blacklight.search.search_results_header') %></h2>

  <% @page_title = t('blacklight.search.title', :application_name => application_name) %>

  <% extra_head_content << render_opensearch_response_metadata.html_safe %>

  <%= render :partial => 'did_you_mean' %>
  
  <%= render :partial => 'constraints' %>
  
  <ul id="view-tabs" class="nav nav-tabs">
    <li class="active"><a class="btn-view" href="#view-list" data-toggle="tab" data-view="list">List View</a></li>
    <li><a class="btn-view" href="#view-graph" data-toggle="tab" data-view="graph">Graph View</a></li>
  </ul>
  
  <div class="tab-content">
    <div class="tab-pane fade in active" id="view-list">
      <%= render 'sort_and_per_page' %>
    
      <h2 class="hide-text"><%= t('blacklight.search.search_results') %></h2>
      
      <%= render_document_index %>
    
      <%= render 'results_pagination' %>
    </div>
    <div class="tab-pane fade in" id="view-graph">
      <%= render :partial => 'results_header' %>
      
      <%= render :partial => 'graph' %>
    </div>
  </div>
</div>