lws_blacklight/config/routes.rb
require 'lucid/prism' 

LwsBlacklight::Application.routes.draw do
  get 'catalog/opensearch', :as => "opensearch_catalog"
  get 'catalog/email', :as => "email_catalog"
  post 'catalog/email'
  get "catalog/facet/:id", :to => 'catalog#facet', :as => 'catalog_facet'
  get "catalog", :to => 'catalog#index', :as => 'catalog_index'

  get 'catalog/:collection_id', :to => 'catalog#index', :as => 'collection' 

  get 'bookmarks' => 'bookmarks#index', :as => 'bookmarks'
  delete 'bookmarks/clear' => 'bookmarks#clear', :as => 'clear_bookmarks'
  put 'bookmark' => 'bookmarks#create', :as => 'bookmark'
  delete 'bookmark' => 'bookmarks#destroy', :as => 'bookmark'

  Blacklight.add_routes(self, :except => [:bookmarks, :catalog])
  
  devise_for :users
  
  match "prism" => Lucid::Prism, :anchor => false 
  
  root :to => "collections#index"
  

end

lws_blacklight/app/views/layouts/_head.html.erb
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= h(@page_title || application_name) %></title>
  <link href="<%= opensearch_catalog_path(:format => 'xml', :only_path => false) %>" title="<%= application_name%>" type="application/opensearchdescription+xml" rel="search"/>
  <%= favicon_link_tag asset_path('favicon.ico') %>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag 'modernizr' %>
  <%= csrf_meta_tags %>
  <%= raw(render_head_content) %> 
</head>

lws_blacklight/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="no-js">
  <%= render :partial => 'layouts/head' %>
  <body class="<%= render_body_class %>">
    <div id="wrap">
      <%= render :partial => 'shared/header_navbar' %>
      <div id="ajax-modal" class="modal hide fade" tabindex="-1"></div>
      
      <!-- /container -->
      <div id="main-container" class="container">
        <%= yield %>
      </div>
    </div>
    <%= render :partial => 'shared/footer' %>
  </body>
</html>

lws_blacklight/app/views/layouts/lws_blacklight.html.erb
<!DOCTYPE html>
<html class="no-js">
  <%= render :partial => 'layouts/head' %>
  <% onload_text = "$('input#q').focus();" if params[:q].to_s.empty? and params[:f].to_s.empty? and params[:id].nil? %>
  <body onload="<%= onload_text %>" class="<%= render_body_class %>">
    <div id="wrap">
      <%= render :partial => 'shared/header_navbar' %>
      <div id="ajax-modal" class="modal hide fade" tabindex="-1"></div>
  
      <!-- /container -->
      <div id="main-container" class="container <%= 'has_constraints' if query_has_constraints? %>">
        <!-- Top bar -->
        <div id="search-found" class="row hidden-phone">
          <%= topbar_items.join('').html_safe %>
        </div>
        <!-- /Top bar -->
        <div class="row">
          <div class="span12">
            <div id="main-flashes">
              <%= render :partial=>'/flash_msg' %>
            </div>
          </div>    
        </div>              
        <div class="row">
          <%= yield %>
       </div>   
      </div>
    </div>
    <%= render :partial => 'shared/footer' %>
    <div id="load-javascripts">
      <%= javascript_include_tag 'application' %>
    </div>
  </body>
</html>